DISTRO = "asterquanta"
DISTRO_NAME = "AsterQuanta OS"
DISTRO_VERSION = "1.0.0"
DISTRO_CODENAME = "vega"

require conf/distro/poky.conf

# Init réel = systemd (pas sysvinit)
INIT_MANAGER = "systemd"
DISTRO_FEATURES:append = " systemd wayland pam usrmerge"
DISTRO_FEATURES_BACKFILL_CONSIDERED = "sysvinit"
VIRTUAL-RUNTIME_init_manager = "systemd"
VIRTUAL-RUNTIME_login_manager = "systemd"

# Paquets applicatifs: ipk (opkg), leger et standard en embarque
PACKAGE_CLASSES = "package_ipk"

# Systeme de fichiers persistant avec snapshots reels
DISTRO_FEATURES:append = " btrfs"

# RAUC (update/rollback A/B reel)
DISTRO_FEATURES:append = " rauc"

# Securite: PAM + verification de signature obligatoire sur les bundles
RAUC_KEYRING_PATH ?= "${THISDIR}/../../recipes-core/rauc/files/keyring.pem"
