# meta-asterquanta layer configuration

BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "asterquanta"
BBFILE_PATTERN_asterquanta = "^${LAYERDIR}/"
BBFILE_PRIORITY_asterquanta = "10"

LAYERSERIES_COMPAT_asterquanta = "scarthgap"

LAYERDEPENDS_asterquanta = "core rauc"

WKS_FILE_DEPENDS:append = " parted-native"
